easy_admin:
    design:
        form_theme: # Both themes are for ckeditor integration
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"

        menu:
            - Theme
            - Page
            - { label: 'Missions' }
            - Mission
            - Sensor

    entities:
        Theme:
            class: App\Entity\MissionTheme

            list:
                actions:
                    view:
                        label: View
                        type: route
                        name: theme_show

                fields:
                    - property: title
                    - property: icon
                    - createdBy
                    - createdAt

            form:
                fields:
                    - property: title
                    - property: description
                      type: fos_ckeditor
                      # type_options: { 'config': { 'toolbar': [ { name: 'styles', items: ['Bold', 'Italic', 'BulletedList', 'Link'] } ] } } }
                    - property: icon

        Page:
            class: App\Entity\CmsPage

            list:
                # collapse_actions: true

                actions:
                    view:
                        label: View
                        type: route
                        name: cms_show

                fields:
                    - property: title
                    - property: type
                    - property: slug
                    - property: image
                      type: image
                      base_path: '%app.path.cms_images%'
                    - property: parent
                    - property: position
                    - property: children
                    - property: published
                    - property: createdAt
                    - property: updatedAt
                    - property: createdBy
                    - property: updatedBy

            show:
                fields:
                    - property: title
                    - property: slug
                    - property: type
                    - property: parent
                    - property: position
                    - property: children
                    - property: published
                    - property: createdAt
                    - property: updatedAt
                    - property: createdBy
                    - property: updatedBy

            form:
                fields:
                    - property: title
                    - property: slug
                    - property: published
                    - property: type
                      type: choice
                      type_options:
                          choices: '%app.cms.page.type.choices%'
                    - property: content
                      type: fos_ckeditor
                      # type_options: { 'config': { 'toolbar': [ { name: 'styles', items: ['Bold', 'Italic', 'BulletedList', 'Link'] } ] } } }
                    - property: imageFile
                      type: vich_image
                    - property: parent
                    - property: position

        Mission:
            class: App\Entity\Mission
            disabled_actions: ['new', 'edit', 'delete']

            list:
                actions:
                    show:
                        name: Show
                    view:
                        label: View
                        type: route
                        name: mission_show

                fields:
                    - property: title
                    - property: createdAt
                    - property: finishedAt
                    - property: missionSensors

        Sensor:
            class: App\Entity\Sensor
            disabled_actions: ['new', 'delete']

            list:
                actions: ['show']

                fields:
                    - property: id
                    - property: createdAt
                    - property: name
                    - property: type

            show:
                fields:
                    - property: id
                    - property: createdAt
                    - property: data
                    - property: name
                    - property: type

            edit:
                fields:
                    - property: name
                    - property: type

        MissionSensor:
            class: App\Entity\MissionSensor
            disabled_actions: ['new', 'edit', 'delete']

            list:
                actions: ['show']

                fields:
                    - property: id
                    - property: createdAt
                    - property: mission
                    - property: sensor

            show:
                fields:
                    - property: id
                    - property: createdAt
                    - property: mission
                    - property: sensor
