twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']

    globals:
        cms_images_base_url: '%app.path.cms_images%'

    date:
        format: d/m/Y H:i:s
        timezone: Europe/Copenhagen
